version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: focusflow_db
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: ooooo
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    expose:
      - "5432"

